/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.summative_project;

import java.io.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
        
/**
 *
 * @author spate8
 */
public class FavouritesPage extends javax.swing.JFrame {

    String dir = System.getProperty("user.dir");
    String fileName = dir + "\\src\\my\\summative_project\\favBooks.txt";
    ArrayList<String> bookList = new ArrayList<>();
    File bookFile = new File(fileName);
    boolean favFound = false;
    String tempString = "";
    String longString = "";
    String favBook = "";
    
    /**
    Creates new form FavouritesPage
    */
    
    public FavouritesPage() {
        initComponents();
        
        //read text from file
        try(Scanner readFile = new Scanner (bookFile))
        {
            while (readFile.hasNext())
            {
                //update book into temporary String and update accumulated String before adding to list
                tempString = readFile.nextLine();
                longString = longString + tempString + "\n";
                bookList.add(tempString); 
            }
        }
        catch (FileNotFoundException e)
        {
            e.printStackTrace();
        }
        
        //set read text into text pane
        favTextPane.setText(longString);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        favPanel = new javax.swing.JPanel();
        favTextField = new javax.swing.JTextField();
        favSearch = new javax.swing.JButton();
        favMessageLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        favTextPane = new javax.swing.JTextPane();
        favRemoveButton = new javax.swing.JButton();
        favSave = new javax.swing.JButton();
        favAddButton = new javax.swing.JButton();
        favSidePanel = new javax.swing.JPanel();
        returnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(576, 416));

        favPanel.setBackground(new java.awt.Color(249, 240, 230));
        favPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Favourites/Wish List", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18))); // NOI18N

        favTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                favTextFieldActionPerformed(evt);
            }
        });

        favSearch.setBackground(new java.awt.Color(255, 225, 232));
        favSearch.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        favSearch.setText("Search Book");
        favSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                favSearchActionPerformed(evt);
            }
        });

        favMessageLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        favTextPane.setBackground(new java.awt.Color(249, 240, 230));
        favTextPane.setOpaque(false);
        jScrollPane1.setViewportView(favTextPane);

        favRemoveButton.setBackground(new java.awt.Color(255, 225, 232));
        favRemoveButton.setText("Remove Book");
        favRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                favRemoveButtonActionPerformed(evt);
            }
        });

        favSave.setBackground(new java.awt.Color(255, 225, 232));
        favSave.setText("Save");
        favSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                favSaveActionPerformed(evt);
            }
        });

        favAddButton.setBackground(new java.awt.Color(255, 225, 232));
        favAddButton.setText("Add Book");
        favAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                favAddButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout favPanelLayout = new javax.swing.GroupLayout(favPanel);
        favPanel.setLayout(favPanelLayout);
        favPanelLayout.setHorizontalGroup(
            favPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(favPanelLayout.createSequentialGroup()
                .addGroup(favPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(favPanelLayout.createSequentialGroup()
                        .addGroup(favPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(favPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(favMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(favPanelLayout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(favAddButton)
                                .addGap(18, 18, 18)
                                .addComponent(favSave)
                                .addGap(18, 18, 18)
                                .addComponent(favRemoveButton)))
                        .addGap(0, 53, Short.MAX_VALUE))
                    .addGroup(favPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(favPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(favPanelLayout.createSequentialGroup()
                                .addComponent(favTextField)
                                .addGap(18, 18, 18)
                                .addComponent(favSearch))
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        favPanelLayout.setVerticalGroup(
            favPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(favPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(favPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(favTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(favSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(favMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(favPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(favRemoveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(favSave, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(favAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        favSidePanel.setBackground(new java.awt.Color(255, 225, 232));

        returnBack.setBackground(new java.awt.Color(234, 153, 153));
        returnBack.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        returnBack.setText("Main Menu\n");
        returnBack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        returnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout favSidePanelLayout = new javax.swing.GroupLayout(favSidePanel);
        favSidePanel.setLayout(favSidePanelLayout);
        favSidePanelLayout.setHorizontalGroup(
            favSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, favSidePanelLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(returnBack)
                .addGap(20, 20, 20))
        );
        favSidePanelLayout.setVerticalGroup(
            favSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, favSidePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(returnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(favPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(favSidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(favPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(favSidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void favTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_favTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_favTextFieldActionPerformed

    private void favSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_favSearchActionPerformed
        // TODO add your handling code here:
        
        favBook = favTextField.getText();
        
        //to see if favBook is already in the book list
        favFound = bookList.contains(favBook);
        
        //logic to display label meessage
        if(favFound == false)
        {
            favMessageLabel.setText("The book " + favBook + " is not in your Favourites List.");
        }
        else
        {
            favMessageLabel.setText("The book " + favBook + " is in your Favourites List!");
        }
    }//GEN-LAST:event_favSearchActionPerformed

    private void returnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBackActionPerformed
        // TODO add your handling code here:
        MainPage main = new MainPage();
        main.setVisible(true);
        dispose();
    }//GEN-LAST:event_returnBackActionPerformed

    private void favSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_favSaveActionPerformed
     
        //save results into file
        try
        {
            FileWriter writeFile = new FileWriter(dir + "\\src\\my\\summative_project\\favBooks.txt");
            BufferedWriter buffWrite = new BufferedWriter(writeFile);
            for(int i = 0; i < bookList.size(); i++)
            {
                buffWrite.write(bookList.get(i));
                buffWrite.newLine();
            }
          buffWrite.close();
        }
        catch (FileNotFoundException e){
            System.out.println("File not found");
        } 
        catch (IOException ex) {
            Logger.getLogger(FavouritesPage.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }//GEN-LAST:event_favSaveActionPerformed

    private void favAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_favAddButtonActionPerformed
  
        favBook = favTextField.getText();
        
        //add book to the list
        bookList.add(favBook); 
        
        //reset longString variable
        longString = "";
        for(int i = 0; i < bookList.size(); i++)
        {
            //update longString variable
            longString = longString + bookList.get(i) + "\n";
        }
        
        //set new added text to text pane
        favTextPane.setText(longString);
    }//GEN-LAST:event_favAddButtonActionPerformed

    private void favRemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_favRemoveButtonActionPerformed

        favBook = favTextField.getText();
        
        //add book to the list
        bookList.remove(favBook);
        
        //reset longString variable
        longString = "";
        for(int i = 0; i < bookList.size(); i++)
        {
            //update longString variable
            longString = longString + bookList.get(i) + "\n";
        }
        
        //set new removed text to text pane
        favTextPane.setText(longString);
    }//GEN-LAST:event_favRemoveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FavouritesPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FavouritesPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FavouritesPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FavouritesPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FavouritesPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton favAddButton;
    private javax.swing.JLabel favMessageLabel;
    private javax.swing.JPanel favPanel;
    private javax.swing.JButton favRemoveButton;
    private javax.swing.JButton favSave;
    private javax.swing.JButton favSearch;
    private javax.swing.JPanel favSidePanel;
    private javax.swing.JTextField favTextField;
    public javax.swing.JTextPane favTextPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton returnBack;
    // End of variables declaration//GEN-END:variables
}
