/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.summative_project;

import java.io.IOException;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;
import java.util.Random;

/**
 *
 * @author Richelle
 */
public class RecsPage extends javax.swing.JFrame {

    /**
     * Creates new form RecsPage
     */
    public RecsPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        greenRecsPane = new javax.swing.JPanel();
        backToMainMenuPage = new javax.swing.JButton();
        recsMainPanel = new javax.swing.JPanel();
        mysteryButton1 = new javax.swing.JButton();
        fantasyButton1 = new javax.swing.JButton();
        sciFiButton1 = new javax.swing.JButton();
        nonFictionButton1 = new javax.swing.JButton();
        horrorButton1 = new javax.swing.JButton();
        romanceButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        recsTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        greenRecsPane.setBackground(new java.awt.Color(217, 234, 211));
        greenRecsPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        backToMainMenuPage.setBackground(new java.awt.Color(234, 153, 153));
        backToMainMenuPage.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        backToMainMenuPage.setText("Main Menu\n");
        backToMainMenuPage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        backToMainMenuPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMainMenuPageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout greenRecsPaneLayout = new javax.swing.GroupLayout(greenRecsPane);
        greenRecsPane.setLayout(greenRecsPaneLayout);
        greenRecsPaneLayout.setHorizontalGroup(
            greenRecsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(greenRecsPaneLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(backToMainMenuPage)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        greenRecsPaneLayout.setVerticalGroup(
            greenRecsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, greenRecsPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backToMainMenuPage, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        recsMainPanel.setBackground(new java.awt.Color(249, 240, 230));
        recsMainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Recommendations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18))); // NOI18N

        mysteryButton1.setBackground(new java.awt.Color(183, 227, 200));
        mysteryButton1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        mysteryButton1.setText("Mystery");
        mysteryButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mysteryButton1ActionPerformed(evt);
            }
        });

        fantasyButton1.setBackground(new java.awt.Color(217, 234, 211));
        fantasyButton1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        fantasyButton1.setText("Fantasy");
        fantasyButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fantasyButton1ActionPerformed(evt);
            }
        });

        sciFiButton1.setBackground(new java.awt.Color(183, 227, 200));
        sciFiButton1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        sciFiButton1.setText("Sci-Fi");
        sciFiButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sciFiButton1ActionPerformed(evt);
            }
        });

        nonFictionButton1.setBackground(new java.awt.Color(217, 234, 211));
        nonFictionButton1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        nonFictionButton1.setText("Non-fiction");
        nonFictionButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nonFictionButton1ActionPerformed(evt);
            }
        });

        horrorButton1.setBackground(new java.awt.Color(183, 227, 200));
        horrorButton1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        horrorButton1.setText("Horror");
        horrorButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horrorButton1ActionPerformed(evt);
            }
        });

        romanceButton1.setBackground(new java.awt.Color(217, 234, 211));
        romanceButton1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        romanceButton1.setText("Romance");
        romanceButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                romanceButton1ActionPerformed(evt);
            }
        });

        recsTextArea.setEditable(false);
        recsTextArea.setBackground(new java.awt.Color(249, 240, 230));
        recsTextArea.setColumns(20);
        recsTextArea.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        recsTextArea.setLineWrap(true);
        recsTextArea.setRows(5);
        jScrollPane2.setViewportView(recsTextArea);

        javax.swing.GroupLayout recsMainPanelLayout = new javax.swing.GroupLayout(recsMainPanel);
        recsMainPanel.setLayout(recsMainPanelLayout);
        recsMainPanelLayout.setHorizontalGroup(
            recsMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recsMainPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(recsMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(romanceButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horrorButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mysteryButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fantasyButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sciFiButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nonFictionButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        recsMainPanelLayout.setVerticalGroup(
            recsMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, recsMainPanelLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(recsMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(recsMainPanelLayout.createSequentialGroup()
                        .addComponent(horrorButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(romanceButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mysteryButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fantasyButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sciFiButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nonFictionButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(recsMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(greenRecsPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(recsMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(greenRecsPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backToMainMenuPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMainMenuPageActionPerformed
        MainPage main = new MainPage();
        main.setVisible(true);
        dispose();
    }//GEN-LAST:event_backToMainMenuPageActionPerformed

    private void mysteryButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mysteryButton1ActionPerformed
        getRec("https://www.goodreads.com/shelf/show/mystery-thrillers");
    }//GEN-LAST:event_mysteryButton1ActionPerformed

    private void romanceButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_romanceButton1ActionPerformed
        getRec("https://www.goodreads.com/shelf/show/must-read-romance");
    }//GEN-LAST:event_romanceButton1ActionPerformed

    private void fantasyButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fantasyButton1ActionPerformed
        getRec("https://www.goodreads.com/shelf/show/fantasy");
    }//GEN-LAST:event_fantasyButton1ActionPerformed

    private void horrorButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horrorButton1ActionPerformed
        getRec("https://www.goodreads.com/shelf/show/horror");
    }//GEN-LAST:event_horrorButton1ActionPerformed

    private void nonFictionButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nonFictionButton1ActionPerformed
        getRec("https://www.goodreads.com/shelf/show/best-nonfiction");
    }//GEN-LAST:event_nonFictionButton1ActionPerformed

    private void sciFiButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sciFiButton1ActionPerformed
        getRec("https://www.goodreads.com/shelf/show/science-fiction");
    }//GEN-LAST:event_sciFiButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void getRec(String link){
        //clear text area
        Random rand = new Random();
        recsTextArea.setText("");
                      
        //generate 5 random, but unique numbers
        int index[] = new int[5]; 
            int n = 0;
            boolean found;

            while(n<5){
                found = false;
                int current = rand.nextInt(50);

                //linear search to check if random index is not unique
                for(int value:index){
                    if (value==current){
                        found = true;
                        break;
                    }
                }
                //add random value to the array
                if (!found){
                    index[n] = current;
                    n++;
                }
            }
        
        String url = link;
        
        try{
            //connect to website and get all book titles
            Document doc = Jsoup.connect(url).userAgent("Me").get();            
            Elements temp = doc.select(".bookTitle");
            
            //display book titles
            for(int val:index){
                String title;
                //get title
                title = temp.get(val).getElementsByTag("a").first().text();
                //remove text that follows the book title
                int splitIndex = title.indexOf("(");
                title = title.substring(0,splitIndex);
                recsTextArea.append("\n"+"- "+title+"\n");            
            }
            
            
        }
        catch(IOException e){
            e.printStackTrace();
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecsPage().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToMainMenuPage;
    private javax.swing.JButton fantasyButton1;
    private javax.swing.JPanel greenRecsPane;
    private javax.swing.JButton horrorButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton mysteryButton1;
    private javax.swing.JButton nonFictionButton1;
    private javax.swing.JPanel recsMainPanel;
    private javax.swing.JTextArea recsTextArea;
    private javax.swing.JButton romanceButton1;
    private javax.swing.JButton sciFiButton1;
    // End of variables declaration//GEN-END:variables
}
