/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.summative_project;

import java.io.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Richelle
 */
public class WishPage extends javax.swing.JFrame {

    String dir = System.getProperty("user.dir");
    String filesName = dir + "\\src\\my\\summative_project\\WishBooks.txt";
    ArrayList<String> booksList = new ArrayList<>();
    File booksFile = new File(filesName);
    boolean wishFound = false;
    String temporaryString = "";
    String longString = "";
    String wishBook = "";
   
    
    /**
     * Creates new form WishPage
     */
    public WishPage() {
        initComponents();
         
        //read text from file
        try(Scanner readFile = new Scanner (booksFile))
        {
            while (readFile.hasNext())
            {
                //update book into temporary String and update accumulated String before adding to list
                temporaryString = readFile.nextLine();
                longString = longString + temporaryString + "\n";
                booksList.add(temporaryString); 
            }
        }
        catch (FileNotFoundException e)
        {
            e.printStackTrace();
        }
        
        //set read text into text pane
        wishTextPane.setText(longString);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wishSidePanel = new javax.swing.JPanel();
        returnBack = new javax.swing.JButton();
        wishPanel = new javax.swing.JPanel();
        wishTextField = new javax.swing.JTextField();
        wishSearch = new javax.swing.JButton();
        wishMessageLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        wishTextPane = new javax.swing.JTextPane();
        wishRemoveButton = new javax.swing.JButton();
        wishSave = new javax.swing.JButton();
        wishAddButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        wishSidePanel.setBackground(new java.awt.Color(237, 225, 255));

        returnBack.setBackground(new java.awt.Color(234, 153, 153));
        returnBack.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        returnBack.setText("Main Menu\n");
        returnBack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        returnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout wishSidePanelLayout = new javax.swing.GroupLayout(wishSidePanel);
        wishSidePanel.setLayout(wishSidePanelLayout);
        wishSidePanelLayout.setHorizontalGroup(
            wishSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, wishSidePanelLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(returnBack)
                .addGap(20, 20, 20))
        );
        wishSidePanelLayout.setVerticalGroup(
            wishSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, wishSidePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(returnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        wishPanel.setBackground(new java.awt.Color(249, 240, 230));
        wishPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Wish List", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18))); // NOI18N

        wishTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wishTextFieldActionPerformed(evt);
            }
        });

        wishSearch.setBackground(new java.awt.Color(237, 225, 255));
        wishSearch.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        wishSearch.setText("Search Book");
        wishSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wishSearchActionPerformed(evt);
            }
        });

        wishMessageLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        wishTextPane.setEditable(false);
        wishTextPane.setBackground(new java.awt.Color(249, 240, 230));
        wishTextPane.setOpaque(false);
        jScrollPane1.setViewportView(wishTextPane);

        wishRemoveButton.setBackground(new java.awt.Color(237, 225, 255));
        wishRemoveButton.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        wishRemoveButton.setText("Remove Book");
        wishRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wishRemoveButtonActionPerformed(evt);
            }
        });

        wishSave.setBackground(new java.awt.Color(237, 225, 255));
        wishSave.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        wishSave.setText("Save");
        wishSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wishSaveActionPerformed(evt);
            }
        });

        wishAddButton.setBackground(new java.awt.Color(237, 225, 255));
        wishAddButton.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        wishAddButton.setText("Add Book");
        wishAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wishAddButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout wishPanelLayout = new javax.swing.GroupLayout(wishPanel);
        wishPanel.setLayout(wishPanelLayout);
        wishPanelLayout.setHorizontalGroup(
            wishPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wishPanelLayout.createSequentialGroup()
                .addGroup(wishPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wishPanelLayout.createSequentialGroup()
                        .addGroup(wishPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(wishPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(wishMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(wishPanelLayout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(wishAddButton)
                                .addGap(18, 18, 18)
                                .addComponent(wishSave)
                                .addGap(18, 18, 18)
                                .addComponent(wishRemoveButton)))
                        .addGap(0, 53, Short.MAX_VALUE))
                    .addGroup(wishPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(wishPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(wishPanelLayout.createSequentialGroup()
                                .addComponent(wishTextField)
                                .addGap(18, 18, 18)
                                .addComponent(wishSearch))
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        wishPanelLayout.setVerticalGroup(
            wishPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wishPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(wishPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wishTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wishSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wishMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(wishPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wishRemoveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wishSave, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wishAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(wishPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(wishSidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wishPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(wishSidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBackActionPerformed
        // TODO add your handling code here:
        MainPage main = new MainPage();
        main.setVisible(true);
        dispose();
    }//GEN-LAST:event_returnBackActionPerformed

    private void wishTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wishTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wishTextFieldActionPerformed

    private void wishSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wishSearchActionPerformed
        // TODO add your handling code here:

        wishBook = wishTextField.getText();

        //to see if wishBook is already in the book list
        wishFound = booksList.contains(wishBook);

        //logic to display label meessage
        if(wishFound == false)
        {
            wishMessageLabel.setText("The book " + wishBook + " is not in your Wish List.");
        }
        else
        {
            wishMessageLabel.setText("The book " + wishBook + " is in your Wish List!");
        }
    }//GEN-LAST:event_wishSearchActionPerformed

    private void wishRemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wishRemoveButtonActionPerformed

        wishBook = wishTextField.getText();

        //add book to the list
        booksList.remove(wishBook);

        //reset longString variable
        longString = "";
        for(int i = 0; i < booksList.size(); i++)
        {
            //update longString variable
            longString = longString + booksList.get(i) + "\n";
        }

        //set new removed text to text pane
        wishTextPane.setText(longString);
    }//GEN-LAST:event_wishRemoveButtonActionPerformed

    private void wishSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wishSaveActionPerformed

        //save results into file
        try
        {
            FileWriter writeFile = new FileWriter(dir + "\\src\\my\\summative_project\\WishBooks.txt");
            BufferedWriter buffWrite = new BufferedWriter(writeFile);
            for(int i = 0; i < booksList.size(); i++)
            {
                buffWrite.write(booksList.get(i));
                buffWrite.newLine();
            }
            buffWrite.close();
        }
        catch (FileNotFoundException e){
            System.out.println("File not found");
        }
        catch (IOException ex) {
            Logger.getLogger(WishPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_wishSaveActionPerformed

    private void wishAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wishAddButtonActionPerformed

        wishBook = wishTextField.getText();

        //add book to the list
        booksList.add(wishBook);

        //reset longString variable
        longString = "";
        for(int i = 0; i < booksList.size(); i++)
        {
            //update longString variable
            longString = longString + booksList.get(i) + "\n";
        }

        //set new added text to text pane
        wishTextPane.setText(longString);
    }//GEN-LAST:event_wishAddButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WishPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WishPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WishPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WishPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WishPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton returnBack;
    private javax.swing.JButton wishAddButton;
    public javax.swing.JLabel wishMessageLabel;
    private javax.swing.JPanel wishPanel;
    private javax.swing.JButton wishRemoveButton;
    private javax.swing.JButton wishSave;
    private javax.swing.JButton wishSearch;
    private javax.swing.JPanel wishSidePanel;
    private javax.swing.JTextField wishTextField;
    public javax.swing.JTextPane wishTextPane;
    // End of variables declaration//GEN-END:variables
}
